import type { Metadata } from "next";
import {Nunito } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

import {
  ClerkProvider,
} from '@clerk/nextjs'
import { ExitModal } from "@/components/modal/exit-modal";
import { HeartsModal } from "@/components/modal/hearts-modal";
import { PracticeModal } from "@/components/modal/practice-modal";


const font = Nunito({
  //variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <ClerkProvider>
      <body
        className={`${font.className}`}
      >
        <Toaster/>
        <ExitModal />
        <HeartsModal />
        <PracticeModal />
        {children}
      </body>
      </ClerkProvider>
    </html>
  );
}
